# Generated by Django 2.2.12 on 2020-04-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191230_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='nameserver2_ip',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='nameserver_ip',
        ),
    ]
